#### **IMPORTANDO LIBRERÍA NUMPY**

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int64')

##### Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [11]:
promedio = np.mean(arreglo)
promedio

np.float64(5.5)

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [12]:
mediana = np.median(arreglo)
mediana

np.float64(5.5)

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

np.float64(2.8722813232690143)

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>



In [ ]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.32598112, 0.73913426, 0.53768767, 0.50105155, 0.99502414,
       0.35229048, 0.73558863, 0.06375748, 0.42212204, 0.49264654])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.17459326, 0.1313927 , 0.35233668],
       [0.57751989, 0.25523325, 0.98369292],
       [0.70956353, 0.86846922, 0.53385919]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [21]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([607, 379, 678, 513, 821,  60, 394, 403, 795, 151], dtype=int32)

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [20]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[19, 18, 84, 26, 28,  9, 49, 87, 80, 37],
       [45, 74, 13, 26, 45, 41, 31, 75, 79, 15],
       [51, 51, 20, 55, 48, 29, 74, 55, 18, 39],
       [67, 66, 97, 17, 27, 53, 61, 42, 62, 81],
       [15, 47, 33, 67, 74, 94, 98, 48, 12, 27],
       [13, 84, 64, 56, 80,  4, 98, 12, 64, 55],
       [41, 56, 46, 67, 54,  7, 98, 19, 23, 19],
       [62, 86, 77, 23, 89, 39, 77, 75, 99, 88],
       [88, 22, 89, 61, 85,  4, 10, 68, 55, 10],
       [46, 44, 22, 74, 41, 46, 88, 45, 54,  5]], dtype=int32)