#### **IMPORTANDO LIBRERÍA NUMPY**

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int64')

##### Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [11]:
promedio = np.mean(arreglo)
promedio

np.float64(5.5)

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [12]:
mediana = np.median(arreglo)
mediana

np.float64(5.5)

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

np.float64(2.8722813232690143)

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>



In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.48460088, 0.80144187, 0.92456158, 0.34611271, 0.15021943,
       0.64705471, 0.67881782, 0.27667258, 0.21519624, 0.76346728])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.43096089, 0.96611901, 0.50827335],
       [0.07772414, 0.17046352, 0.05715935],
       [0.45464763, 0.08419818, 0.92627734]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([853, 962, 245, 397,  47, 402, 293, 342, 153, 729], dtype=int32)

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [20]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 25,   4,  32,  89,  34,  71,  34,  52,  33,  65],
       [ 36,   8,  88,  93,  63,  70,  99,   6,  47,  37],
       [ 97,  49,  84,  84,  93,  22,   5,  85,  64,  60],
       [ 10,  43,  88,  48, 100,  76,  77,   6,  91,  34],
       [ 19,  64,   8,  75,  55,   7,  51,  45,   8,  86],
       [ 27,  15,  12,  51,  35,  73,  88,  77,   8,  14],
       [  8,  57,  87,  69,  82,  77,  47,  27,  90,  81],
       [ 14,   5,   9,  51,  90,  71,  18,  65,  46,  69],
       [ 78,  92,  94,  50,  52,  64,   1,  17,  67,  79],
       [ 28,  96,  29,  92,  90,  73,  73,  97,  68,  32]], dtype=int32)